In [1]:
import pandas as pd, matplotlib.pyplot as plt, seaborn as sns

df = pd.read_csv('dataset/online food delivery dataset.csv')

df_clean = df.drop(columns=['latitude','longitude','Pin code'])

df_clean

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,Output,Feedback,Unnamed: 13
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Regular,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,Frequent,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,Frequent,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,Frequent,Yes,Positive,Yes

In [6]:
df_clean.groupby('Customer Type')['Family size'].value_counts(normalize=True).unstack().round(2).mul(100).fillna(0)

Family size        1     2     3     4     5     6
Customer Type
Frequent         0.0   0.0   0.0  43.0  37.0  20.0
New            100.0   0.0   0.0   0.0   0.0   0.0
Regular          0.0  46.0  54.0   0.0   0.0   0.0

In [10]:
df_clean.groupby('Customer Type')['Occupation'].value_counts(normalize=True).unstack().round(2).mul(100).fillna(0)

Occupation     Employee  House wife  Self Employeed  Student
Customer Type
Frequent           33.0         5.0            13.0     49.0
New                33.0         0.0            12.0     54.0
Regular            28.0         1.0            15.0     56.0